#!/usr/bin/env python3
# coding: utf-8
# Julien Pecqueur <julien@peclu.net>

from sys import argv

if len(argv) != 2:
    print("Usage: fail2ban-getlog <file>")
    print("Extract fail2ban logs to CSV file.")
else:
    f_log = "/var/log/fail2ban.log"
    old = []
    try:
        with open(argv[1], "r") as old_f:
            for line in old_f:
                old.append(line[0:-1])
    except FileNotFoundError:
        print(f'File {argv[1]} not found. Creating empty file.')
        open(argv[1], "a").close()
    print(len(old), "existing line(s).")
    counter = 0
    with open(f_log, "r") as f_in, open(argv[1], "a+") as f_out:
        for line in f_in:
            line = line[0:-1].split(" ")
            if "Ban" in line:
                line = line[-1]+";"+line[0]+";"+line[1][0:-4]
                if not line in old:
                    f_out.write(line + "\n")
                    counter += 1
    print("Added", counter, "new line(s).")